name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 12
      uses: joschi/setup-jdk@v2
      with:
        java-version: '12'
        architecture: 'x64'
    - name: Build with Maven
      run: mvn -B package --file pom.xml -Pxtest
